### ISSUE TITLE
AT-11 : (US2F - As a user, I want information about the Concordia Shuttle services)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#112]
FIX FROM SPRINT 2
**Acceptance Criteria**
Given that I am on the main page of the application, I would like a quick link which will allow me to see the shuttle bus times.  

Added style & give user indication of when the next shuttle is.

To access the schedule 

1.  Click on the burger menu
2. Click on Shuttle Bus Schedule
3. You can switch between which campus shuttle schedule you want to see

Next schedule based on current time

1. From the home view of the map, click on the direction circular button (blue one) on the bottom right.
2. Click on the bus icon in the search area

**Comment by mkshiblu** [comment]
Accepted. The styling could be improved a bit more though. I liked that the tabs are working okay.
