### ISSUE TITLE
AT-3 : (US1C - As a user, I want to easily be able to switch between campuses (SGW & Loyola)):

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#113]
FIX FROM SPRINT 2
**Acceptance Criteria**
Given that I am in the application, I want to see a button that will allow me to switch between campuses labelled SGW and Loyola that when clicked, will move the map to the selected location.

1. Click on the search bar
2. Two buttons will appear SGW and Loy

**Comment by mkshiblu** [comment]
Accepted
