### ISSUE TITLE
AT-25 : (US6A - As a user, I want to be able to explore the application using different languages so that I can use it in my native language)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#114]
FIX FROM SPRINT 2 (it was partially accepted)
**Acceptance Criteria**
In the application, I should have a setting that can allow me to select the language and/or the language should be possibly set via my phone's setting.

1. There is no more Language from the burger menu as you suggested
2. You can switch the language of your phone and the application will adapt

**Comment by mkshiblu** [comment]
Accepted. Changing the language from the device is working pretty well.
