### ISSUE TITLE
AT-9 : (US2D - As a user, I want to have directions from one campus to another (SGW and Loyola))

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#115]
**Acceptance Criteria**
Given that I am in the application and have decided to travel to SGW or Loyola, I want to have on map a drawn path from SGW to Loyola and vice versa depending on what I input in the search bar.

1. Click on the direction button, bottom right hand corner blue circular button
2. Enter Sir George William in the first search box (or Loyola )
3. Enter the destination as the other campus
4. Search

**Comment by mkshiblu** [comment]
Accepted. It crashed one time though when I put Loyola int the first search bar and Concordia in the 2nd one,
