### ISSUE TITLE
AT-7: (US2B - As a user, I want to select my current building as a starting point)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#116]
**Acceptance Criteria**
Given that I am in the application, I want to be able to set my starting point as my current location thus also the current building in which I am located in.
[Helpful user story for this: US1D]

1. Click on the direction button, the blue circular button on the bottom right of the screen
2. Your current location should always be the default starting point

**Comment by mkshiblu** [comment]
Accepted
