### ISSUE TITLE
AT-23 : (US5A - As a user, I want to be able to view points of interest external to Concordia)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#117]
**Acceptance Criteria**
In the application, I want to be able to view other places around Concordia’s campuses.

1. Type in the search bar "coffee shops **near sgw**", "grocery stores **near loy**", "bars **near sgw**"
Note: you can type anything as long as it finishes with either "near loy" or "near sgw"

**Comment by mkshiblu** [comment]
Accepted
