### ISSUE TITLE
AT-17 : (US4A - As a user, I want detailed information about the buildings interior.)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#119]
**Acceptance Criteria**
In the application, I should be able to see specific placements  ACCORDING TO THE FLOOR PLANS PROVIDED of the classrooms on specific floors, Switch between floors and get an updated view plan

Note: We do not have floor plans for every building as this is impossible to do.
1. Click on the Hall Building from the map, you will enter indoor mode

**Comment by mkshiblu** [comment]
Accepted. The building detail view overlaps the floor no. buttons. This overlapping should be handled.
