### ISSUE TITLE
AT-10 : (US2E - As a user, I want to be able to choose my method of transportation.)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#122]
**Acceptance Criteria**
In the application, I would like to see buttons for every available transportation and the information displayed should be adjusted accordingly.

1.  Click on the direction button, circular button on the bottom right 
2. Make sure you enter a starting point and a destination
3. You can click on bus, car, walk, or bike and the path will be readjusted

**Comment by mkshiblu** [comment]
Accepted
