### ISSUE TITLE
Bug-8 Error sending user calendars information

### ISSUE THREAD

**Issue by sebhani** [gisellemartel/CONPASS#143]
**Environment**
Phone: Galaxy Note 5
OS Version: Android 7.0

**Steps to reproduce**
This bug occurred in two places: 
1- Go to Calendar tap in the side menu
2- Login with Google to allow calendar synchronization

**Expected behavior**
Google calendar events are synchronized and functional in the app's calendar

**Current behavior**
The app is crashing when it's going from the logging screen to the fetching screen. The following message is showing up: "TypeError: undefined is not an object (evaluating 'this.props.navigation.state.params.userCalendarsInfo')"

**Comment by mohhef** [comment]
This bug was fixed by @t98b on US3B_MultipleCalenderSync

**Comment by sebhani** [comment]
@mohhef Thanks, we figured it out.
