### ISSUE TITLE
Bug-9 The list of available user calendars isn't showing up

### ISSUE THREAD

**Issue by sebhani** [gisellemartel/CONPASS#144]
**Environment**
Phone: Galaxy Note 5
OS Version: Android 7.0

**Steps to reproduce**
1- You have to be logged out from Google calendar within the app (if not hit sign out button)
2- hit sign in with google
3- you'll see the bug in the transition state

**Expected behavior**
User calendars shall be displayed so that the user can pick which ones to sync

**Current behavior**
The list of available user calendars isn't showing up. Either an empty list is shown or an error with the following message: "this.options is invalid"

**Comment by TalalBazerbachi** [comment]
This bug was fixed by @t98b on US3B_MultipleCalenderSync
