### ISSUE TITLE
AT-14 :  US3C - As a user, I want to get notifications to my next class based on my course schedule synchronized from Google’s calendar

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#152]
1. Add an event in your google calendar where the title includes the word 'conpass'
2. Verify that the start time of the event is correct (or change it)
2. Open the application
3. Connect to google calendar by accessing it through the burger menu (Menu -> Calendar)
4. Refresh the calendar screen if you were previously logged in by swiping down
5. You will need to set a time for when you would like to be notified of the event (i.e. 15)

Scenario: Assuming the current time is 6:30 PM and you set the event to start at 6:45 PM.
From Conpass, you say you want to get notified 14 minutes before the event, you will get notified at 6:31 PM.  The remainder is in terms of minutes as mentioned in the application.

Video showing all the calendar's features: https://vimeo.com/409586795

**Comment by mkshiblu** [comment]
It shows the google web page in-app after authorizing con pass for the google account in Android 28. If I restart the app and go to the calendar, It asks for sign in again and repeats the same thing.  This was also happening with my physical device Android OS 9.0.

I am attaching the steps and the emulator details.

![1](https://user-images.githubusercontent.com/15908043/79807048-d5b3ed00-8337-11ea-9699-664b8554a8de.PNG)
![2](https://user-images.githubusercontent.com/15908043/79807049-d64c8380-8337-11ea-8f66-12b808ee64a4.png)
![3](https://user-images.githubusercontent.com/15908043/79807051-d64c8380-8337-11ea-9137-0677c9f3bbdf.PNG)
![4](https://user-images.githubusercontent.com/15908043/79807053-d6e51a00-8337-11ea-9f5a-ca1f03ceda4f.PNG)
![5](https://user-images.githubusercontent.com/15908043/79807042-d51b5680-8337-11ea-9747-e567a59f0175.PNG)
![6](https://user-images.githubusercontent.com/15908043/79807044-d5b3ed00-8337-11ea-9430-865d8a895425.PNG)
![7](https://user-images.githubusercontent.com/15908043/79807046-d5b3ed00-8337-11ea-9685-6ab6263c2c4f.PNG)

**Comment by mkshiblu** [comment]
ACCEPTED. It's a good extra feature.
