### ISSUE TITLE
AT-21 : (US4E - As a user, I want to be able to select/specify start and end rooms to and from any floor.)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#168]
1. Launch the application
2. Tap on a building that has an interior mode (e.g. Hall building)
3. Once in interior mode, Click the direction button (blue button bottom right-hand side)
4. Enter a starting point (e.g H-103) (on the floor you are currently on) and a destination point (e.g. H-907)
5. A path will be drawn from H-103 to H-907, verify that by navigating to the 9th floor

**Comment by mkshiblu** [comment]
ACCEPTED
