### ISSUE TITLE
AT-20 : (US4D - As a user, I want to find specific amenities in each building.) 

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#169]
1. Launch the application
2.  Click on a building that supports interior mode (i.e. Vanier library ) and tap on 'View interior mode'
3. Click on direction (blue button bottom right hand corner)
4. Type in location (e.g. H-103) and destination (in the suggestions you should have amenities) i.e bathroom for which you can get a path to (e.g H-1 male bathroom)

**Comment by mkshiblu** [comment]
ACCEPTED
