### ISSUE TITLE
AT-13 : (As a user, I want to synchronize multiple Google calendars so that all my calendars’ events are grouped together.)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#170]
1. Go to https://calendar.google.com/calendar/r
2. Create a new calendar (press on the plus button above 'other calendars')
4. Wait until the calendar is created and go back
3. In the checkbox under 'My calendars' choose the newly created calendar ONLY
4. Add multiple events
5. Launch Conpass application
6. In the burger menu click on calendar
7. Login with Google and authorize Conpass to have access to your Calendar
8. You will be able to select which calendars you will like to see in Conpass
9. Select the newly created calendar and your original calendar
10. Now you will see the events from both calendars

Note: do not use preexisting calendars on https://calendar.google.com/calendar/r, a new one has to be created.

Video showing all the calendar's features: https://vimeo.com/409586795

**Comment by mkshiblu** [comment]
As mentioned in a previous issue, clicking the calendar always shows the google sign-in screen.

**Comment by mkshiblu** [comment]
ACCEPTED
