### ISSUE TITLE
AT-22 : (US4F - As a user, I want to select a room on one campus as the start and a room on another campus and the destination.)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#171]
1. Launch the application
3. Make sure you are in the main view of the application where there is only one search bar
4. Tap on a building that supports indoor view and tap on 'View interior mode'
5. Click on the directions button and enter in the first field a location from the current floor of the building you are currently in (e.g H- 403) and as the destination, enter something at the Loyola campus(e.g VL- 122) (if you are currently in Loyola enter something on the SGW campus)
6. A path should be drawn from start to destination

**Comment by mkshiblu** [comment]
ACCEPTED
