### ISSUE TITLE
AT-25 - (US5B - As a user, I want to get map directions to external points of interest.)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#172]
1. Launch the application
2. Make sure you are in the main view of the application where there is only one search bar
3. Tap on a building that supports indoor view and tap on 'View interior mode'
3. Click on the direction button on the bottom right-hand corner (blue button)
4. Enter a starting point (e.g H-201 if you are currently selected on the second floor)
5. Enter a destination outside like a local Tim Hortons

**Comment by mkshiblu** [comment]
ACCEPTED
