### ISSUE TITLE
AT-15 : (US3Ci - As a user, I want to get direction to my next class based on my course schedule and current location.)

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#173]
1. Add an event into your google calendar application
and in the location of the event enter the classroom number (H-101) OR a building name(Hall Building)
1. Launch the application
2. From the burger menu, click on Calendar
3. Log in with google
4. Select your main calendar from 'Available Calendars For Synchronization" (e.g. mohhef@xxxx.xxx)
5. Once in conpass and connected with Google, you can click on the event from the calendar.
    - If events cant be seen refresh the calendar by pulling down
7. Click on 'Get directions' and choose the most appropriate option from the dropdown list( First option)
8. Directions will be shown to the building, in case of an indoor room you can click on the specific building and see the indoor directions as well.

Video showing all the calendar's features: https://vimeo.com/409586795

**Comment by mkshiblu** [comment]
As mentioned in previous issues, the calendar syncing feature is not working on Android 28.

**Comment by mkshiblu** [comment]
ACCEPTED
