### ISSUE TITLE
AT-19 : (US2F -  As a user with special mobility requirements, I want to be able to see directions that have accommodations for those with mobility problems.)

### ISSUE THREAD

**Issue by mohhef** [gisellemartel/CONPASS#177]
1. Launch the application
2. Press on the sidebar menu
3. Press on 'Enable Accessibility'
4. Go into an interior mode of a building and click on 'View Interior Mode' 
5. Press on the circular button at the bottom right
5. Select an origin (e.g. H-101), select a destination (e.g. H-303)
6. A path will be drawn to the destination through the elevator available at your current floor to the destination floor

**Comment by mkshiblu** [comment]
ACCEPTED
