### ISSUE TITLE
US4A: As a user, I want to be able to view the buildings interior.

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#19]
Should have view of floors in each building for which a floor plan in available. User should be able to switch easily between floors of building.

**Comment by MikeG3** [comment]
Detailed information about the building:
-Departments
-Services
-Address
-Accessibility
-Entrance location/coordinates

The information is available here:
http://www.concordia.ca/maps/sgw-campus.html

1. I can webscrape this information if needed, and put it in a JSON file, or another format.
OR
2. We can try to access the information through, through Concordia's website

Any thoughts? .. Ill try to get started on this asap
