### ISSUE TITLE
Software Architecture Design

### ISSUE THREAD

**Issue by gisellemartel** [gisellemartel/CONPASS#4]
## The following diagrams need to be created:
- Component Diagram
- Domain Diagram

## Grading Criteria:
- [ ] Is the domain model detailed enough?
- [ ] Is a component diagram included?
- [ ] Based on the requirements, is there something missing from the domain model?
- [ ] Are the external libraries that the project depends on discussed properly?
- [ ] What are the advantages of the selected libraries over other alternative ones?

**Comment by MikeG3** [comment]
The Domain Model is complete, are you working on the Component Diagram @sebhani ?

**Comment by sebhani** [comment]
@MikeG3 I'm almost done! I need to verify a few details. It's going to be pasted to the document by tomorrow night.

**Comment by MikeG3** [comment]
Great!! :)
Thanks
