### ISSUE TITLE
Knowledge of Campus

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#44]
- [ ] Knowledge of where every class is located
- [ ] Knowledge of campus
- [ ] Knowledge of accessibility (stairs, elevators)
- [ ] Defining where building stops
- [ ] Have the picture of the floor plan - we need to be able to convert the picture to SVG

**Comment by trevornag** [comment]
@MikeG3 any updates?

**Comment by MikeG3** [comment]
Ill be adding a link here with some building information soon, but I still have a lot to work on.

Any updates on the exact data needed? or file types for maps that will be compatible with our project?

**Comment by MikeG3** [comment]
Here is a spread sheet with the raw data about buildings and rooms. I can add/edit attributes or format the data  as needed (to JSON or another data structure)

https://docs.google.com/spreadsheets/d/1RK6741owJUnofRE66shdcZsJwzeuasLAKW0zebzBluY/edit?usp=sharing

Source:
http://www.concordia.ca/maps/sgw-campus.html
http://www.concordia.ca/maps/loyola-campus.html

**Comment by MikeG3** [comment]
I will start collecting floor plans of the buildings next

**Comment by trevornag** [comment]
Sounds Good! @MikeG3 perhaps we can move this card to in progress :)

**Comment by MikeG3** [comment]
See issue #19
