### ISSUE TITLE
CORRECTION: US1C - campus switching Needs proper styling

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#65]
- [x] Campus switch should be pill shaped
- [x] Semi-transparent (opacity/fill)
- [x] Current campus should be highlighted

**Comment by eufekt** [comment]
As part of the accepting criteria, the UI should closely look like this while keeping the currently implemented functionality 
ie:
1.  User clicks on search.
2. User sees the campus switching option.
3. as soon as the user starts typing, the switching functionality disappears.

![Screen Shot 2020-03-19 at 1 38 52 PM](https://user-images.githubusercontent.com/30513164/77097337-032f1300-69e7-11ea-9243-77971d7a2d39.png)

**Comment by GD-Dheer** [comment]
Current UI matches the following UI. Will be updated as recent places is added
![image](https://user-images.githubusercontent.com/25235293/77236565-221fd780-6b96-11ea-9543-60356813181a.png)
