### ISSUE TITLE
US1B: As a user, I want the campus buildings to be easily distinguishable from other surroundings so that I can easily differentiate them from nearby buildings.

### ISSUE THREAD

**Issue by trevornag** [gisellemartel/CONPASS#9]
The buildings should appear with different colors, shapes, overlays and/or highlights for clear visibility

**Comment by trevornag** [comment]
I tested the Concordia API and got a list of the buildings. We should definitely base ourselves on this [Condordia API - list of buildings.txt](https://github.com/gisellemartel/CONPASS/files/4242711/Condordia.API.-.list.of.buildings.txt)

**Comment by mohhef** [comment]
Great resource!
An interactive map could be found [here ](http://www.concordia.ca/maps/sgw-campus.html)too.
They use markers instead of polygons.
