### ISSUE TITLE
Bug-3: WithinBuilding Component excessively slows down the app.

### ISSUE THREAD

**Issue by eufekt** [gisellemartel/CONPASS#93]
The WithinBuilding Component slows down the app due to heavy computation or because data fetching takes too much time.

We also noticed that the phone gets hot with within building.

Reproduce bug:
use the app for 1-2 minutes by dragging or focusing on a building (try US4A branch).
without the withinBuilding component, the app animates beautifully.

Requires further investigation.

**Comment by sebhani** [comment]
Potential solutions:
1- Use shouldComponentUpdate method to solve this problem by preventing the component from rendering if the previous value of buildingDisplayName is similar to the new one.
2- Make fetching of user's current location less frequent (every 5 sec or even 10 sec).
3- Enable the user to choose when to detect which building he is in by clicking a button (this the most guaranteed & straightforward solution).
